### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by suijiheidong** [syhien/CaiNiao-Auto.js#1]
大佬 有兴趣研究下裹裹app的任务脚本吗？？每天做任务挺累，或者抢购的，有偿

**Comment by syhien** [comment]
我这个脚本就是纯兴趣+自用的，有时间我可以试试，就当练手了

（裹裹应该指的是菜鸟吧，应该吧）
具体是哪个任务啊，除了包裹梦工厂、喜气红包（我另一个仓库）还有别的任务吗

然后抢购这个，其实autojs这个东西主要是模拟一些比较机械化的、比较固定的行为，在争分夺秒的场景其实没什么优势
